### ISSUE TITLE
[INCIDENCIA][VISUALIZACIÓN] No se puede acceder a los resultados de una votación

### ISSUE THREAD

**Issue by TCL90** [EGC-GIRATINA/decide#67]
Cuando intentas acceder a los resultados de una votación no se muestra nada, solo que no se ha podido encontrar esa página.
![image](https://user-images.githubusercontent.com/36821243/72225402-6b93eb00-3585-11ea-8fa3-db2d40b88a9f.png)
En la consola en la que se ha ejecutado el comando ./manage.py runserver se muestra lo siguiente:
![image](https://user-images.githubusercontent.com/36821243/72225413-836b6f00-3585-11ea-8dd4-604649c691bf.png)

Al debuggear el archivo views.py del modulo de visualización se ha detectado que el problema esta en esta línea:
![image](https://user-images.githubusercontent.com/36821243/72225424-9ed67a00-3585-11ea-9187-293989206c5b.png)

Una vez que la comentas la página vuelve a funcionar con aparente normalidad. Se ruega alguien que haya participado en esa implementación ayude a reconocer el problema y solucionarlo.

Las pruebas se han realizado con la versión 71.0 de Mozilla Firefox y 79.0.3945.88 de Google Chrome y en ambas se presenta el mismo error.

**Comment by apcm** [comment]
El error ya ha sido arreglado. Cuando todos los votantes habían seleccionado región y no existía ninguno que la hubiese dejado en blanco, la región indefinida no existía en las claves del diccionario y por lo tanto no se podía cambiar esta región indefinida que era un string en blanco por otra clave llamada "No especificado" para que las gráficas se entendiesen mejor.
